<a href="https://colab.research.google.com/github/SmitaS1/deep-learning-challenge/blob/main/Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns =['EIN','NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_type_val_count = application_df['APPLICATION_TYPE'].value_counts()
app_type_val_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_type_val_count[8:].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_types = application_df['CLASSIFICATION'].value_counts()
classification_types

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classifications_cleaned = classification_types.loc[classification_types> 1]
classifications_cleaned

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_types.iloc[5:].index)
cutoff_value_classification = 1883

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [10]:
application_df.dtypes

APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

In [11]:
categorical_list = application_df.dtypes[application_df.dtypes =="object"].index.tolist()
categorical_list

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
df_dummies = pd.get_dummies(application_df)
df_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [14]:
application_df['IS_SUCCESSFUL'].values

array([1, 1, 0, ..., 0, 1, 0])

In [15]:
#scratch work
df_new_application= application_df.drop(columns='IS_SUCCESSFUL')
df_new_application.values

array([['T10', 'Independent', 'C1000', ..., '0', 'N', 5000],
       ['T3', 'Independent', 'C2000', ..., '1-9999', 'N', 108590],
       ['T5', 'CompanySponsored', 'C3000', ..., '0', 'N', 5000],
       ...,
       ['T3', 'CompanySponsored', 'C2000', ..., '0', 'N', 5000],
       ['T5', 'Independent', 'C3000', ..., '0', 'N', 5000],
       ['T3', 'Independent', 'C1000', ..., '1M-5M', 'N', 36500179]],
      dtype=object)

In [16]:
#scratch work
df_dummies['IS_SUCCESSFUL'].values

array([1, 1, 0, ..., 0, 1, 0])

In [17]:
#scratch work
df_clean_dummies = df_dummies.drop(columns='IS_SUCCESSFUL').values
df_clean_dummies

array([[       1,     5000,        0, ...,        0,        1,        0],
       [       1,   108590,        0, ...,        0,        1,        0],
       [       1,     5000,        0, ...,        0,        1,        0],
       ...,
       [       1,     5000,        0, ...,        0,        1,        0],
       [       1,     5000,        0, ...,        0,        1,        0],
       [       1, 36500179,        0, ...,        0,        1,        0]])

In [29]:
# Split our preprocessed data into our features and target arrays
y= df_dummies['IS_SUCCESSFUL'].values
X= df_dummies.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [30]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [31]:
input_features_total = len(X_train[0])
input_features_total

43

In [32]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features_total = len(X_train[0])

hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation = "sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 8)                 352

 dense_4 (Dense)             (None, 5)                 45

 dense_5 (Dense)             (None, 1)                 6

=================================================================
Total params: 403 (1.57 KB)
Trainable params: 403 (1.57 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [33]:
# Compile the model
nn.compile(loss='binary_crossentropy',optimizer='adam',metrics= ['accuracy'])

In [35]:
print(y_train.shape)

(25724,)

In [36]:
# Train the model
fit_model =nn.fit(X_train_scaled,y_train,epochs =100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.6536 - accuracy: 0.6623
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5767 - accuracy: 0.7261
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5623 - accuracy: 0.7287
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7283
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7294
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5555 - accuracy: 0.7296
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5543 - accuracy: 0.7299
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5537 - accuracy: 0.7305
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5535 - accuracy: 0.7308
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5524 - accuracy: 0.7311
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5521 - accuracy: 0.7312
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5517 - accuracy: 0.7315
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5511 - accuracy: 0.7321
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5510 - accuracy: 0.7318
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5503 - accuracy: 0.7320
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5503 - accuracy: 0.7319
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7311
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7313
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7325
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7320
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5490 - accuracy: 0.7334
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5489 - accuracy: 0.7315
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5486 - accuracy: 0.7326
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7324
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7306
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7322
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5483 - accuracy: 0.7335
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7327
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7321
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7319
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7327
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7332
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7322
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7326
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7341
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7326
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7332
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7328
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7336
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7323
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7336
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7320
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7329
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7337
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7339
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7329
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7336
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7326
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7340
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7337
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7336
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7338
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7332
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5464 - accuracy: 0.7338
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7327
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7341
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7342
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7337
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7338
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7330
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7332
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7331
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7333
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7335
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7338
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7343
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7339
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7339
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7334
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7349
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7347
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7327
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7336
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7340
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7335
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7341
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7347
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7336
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7345
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7336
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7338
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7343
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7340
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7341
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7341
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7348
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7342
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7345
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7349
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7342
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7346
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7338
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7347
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7339
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7345
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7355
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7349
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7346
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7343
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7345

In [37]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5595 - accuracy: 0.7263 - 436ms/epoch - 2ms/step
Loss: 0.5595259070396423, Accuracy: 0.7262973785400391

In [41]:
# Export our model to HDF5 file
filepath = r"C:\Users\Shah_\Documents\Rutgers_Data_Science_Boot_Camp_Local\deep-learning-challenge21_to_Github\Starter_Code\Starter_code.h5"
nn.save(filepath,save_format='h5')